number_one= int(input("enter  first number"))
number_two= int(input("enter second number"))
total=number_one+number_two
print("total is " + str(total))
print("total is ",total)
print(f"total is {total}")
number1=str(4)
number2=float("44")
number=int(4)
print(number2+number)
